# Generated by Django 4.0.6 on 2023-12-18 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0002_user_x_user_y'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='x',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='y',
            new_name='longitude',
        ),
    ]
